# Generated by Django 5.0.1 on 2025-03-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.CharField(default='img/realtors/hsquare.png', max_length=200),
        ),
    ]
